### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-surveygizmo-transform#1]
Format should follow: https://github.com/aries-data/aries-activity-typeform-transform

This integration should extract the `question` and `answer` out of the `survey_data` object and append them to overarching object (i.e. with `id`, `date_submitted`, `city`, etc.) as a `key-value` pair. 

For each question id that has `type`: `parent` (i.e. a question with multiple possible responses), create key-value pair for each submitted answer with format `{question_key}_{answer}: {option}`

**Comment by byerc** [comment]
I will focus on this today.

**Comment by byerc** [comment]
I have questions mapped with answers. I still have to add them to their corresponding parent object (i.e. with `id`, `date_submitted`, `city`, etc.). I'll start with that today.

**Comment by byerc** [comment]
refactoring this to handle multiple transform types: focusing on surveyquestion transform at the moment.

**Comment by byerc** [comment]
Working on getting survey answer questions to sink into redshift. Almost there.

**Comment by byerc** [comment]
Finishing up linting.

**Comment by byerc** [comment]
Mike recommended some changes that will help with linting, so I'm going to update with those.

**Comment by benjamingregory** [comment]
@byerc Please update with most recent status.

**Comment by byerc** [comment]
I have not touched this at all.

**Comment by benjamingregory** [comment]
@byerc Can it be moved to QA? If not, please provide what still needs to be done.

**Comment by byerc** [comment]
I've found a few small bugs in this, so I'm looking into these as well so that I can continue field value. 👍

**Comment by byerc** [comment]
Fixing lint errors.
