### ISSUE TITLE
Add label option for headers

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-surveygizmo-transform#2]
**Current Behavior**
The integration by default labels the columns as a cutoff of the original question.
So the question: `"How much did you spend in the past week for the following categories: grocery, movies, gym?"` is turned into the column header `how_much_did_you_spend_in_the_past_week_for_the_following_categor`

**Desired Behavior**
Within the config, the user should be able to flag whether to use a cutoff of the question or label the column as its question id. Each question id is given in the original response as `id` within the `question` objects. 

So...
`config: {
"headerType": "question"
}` 
would lead to the cutoff of the original question (`"how_much_did_you_spend_in_the_past_week_for_the_following_categor": "43"`)

while...
`config: {
"headerType": "qid"
}` 
would lead to the qid being the column.
`"qid_23": "43"`

**Comment by byerc** [comment]
I'll begin working on this today and intermittently when waiting on responses / review changes to be made on AdmitHub.

**Comment by byerc** [comment]
Currently working on this.

**Comment by byerc** [comment]
This should be closed. The new way that we are structuring the output makes this irrelevant.

**Comment by trong-le** [comment]
@benjamingregory can you confirm this can be closed?

**Comment by benjamingregory** [comment]
Yes this can be closed
