### ISSUE TITLE
Wrap transforms in methods

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-surveygizmo-transform#3]
**Current Behavior**
The transform activity expects a SurveyGizmo source response as its input but then transforms that data in a distinct and immutable manner.

**Expected Behavior**
The transform should take into account which type of response is being inputted as part of the config. This will allow partitioned transforms to occur based on the original method called rather than having one generic "transform" behavior that serves a subset of datasets.
```
"config": {
"inputMethod": "getSurveyResponseSubList"
}
```

**Additional Notes**
The current transform behavior should be associated with the method `getSurveyResponseSubList`.

**Comment by byerc** [comment]
Essentially every endpoint should have it's own transform type?

**Comment by benjamingregory** [comment]
Theoretically - essentially when you call a certain method in the source, that same method should be called here to indicate how to transform it.

**Comment by benjamingregory** [comment]
I'd recommend using the same method labeling convention as source to avoid confusion.

**Comment by benjamingregory** [comment]
Closing until other endpoints have clear transform needs.
